---
slug: "audi-a8-fl"
title: "Audi A8 FL"
brand: "Audi"
model: "A8 FL"
publishedAt: "2015-06-01"
lead: "Audi A8 FL - Ku doskonałości  **Nowe Audi A8 - jak każde auto z Ingolstadt - nie zna słowa ‘rewolucja’. Wygląda prawie tak samo konserwatywnie, pod wieloma względami przypomina model nawet o trzy generacje wcześniejszy, ale dzięki nowoczesnej technice i ogromnemu dopracowaniu sta"
originalUrl: ""
tags: ["test"]
---

Audi A8 FL - Ku doskonałości

**Nowe Audi A8 - jak każde auto z Ingolstadt - nie zna słowa ‘rewolucja’. Wygląda prawie tak samo konserwatywnie, pod wieloma względami przypomina model nawet o trzy generacje wcześniejszy, ale dzięki nowoczesnej technice i ogromnemu dopracowaniu stawia czoła najlepszym.**

W samym centrum zimnej i ciemnej już Warszawy spotkaliśmy się z A8 po faceliftingu, by podczas jazdy poznać nowości, jakie zagościły na pokładzie flagowego modelu Audi. Wersja, którą mieliśmy okazję przetestować z pozycji kierowcy to standardowej długości A8 w kolorze &lt;i&gt;Czarna Havana&lt;/i&gt;, a pod maską pracował silnik 4.2 TDI, czyli wysokoprężna V8-ka o mocy 385 KM i potężnym momencie obrotowym wynoszącym maksymalnie 850 Nm. Jest to wzrost względem poprzedniej wersji - moc wzrosła o 34 KM, moment o 50 Nm. 

Z silnikiem współpracuje aksamitny, 8-biegowy tiptronic, którego szybkość i płynność nie pozostawiają najmniejszych watpliwości - skrzynia stosowana również w BMW, Jaguarze, Land Roverze, Volvo i wielu innych markach premium to prawdopodobnie najlepsza konstrukcja na rynku. Razem z napędem quattro i silą jednostki napędowej tworzą potężny zespół napędowy, u którego bardzo trudno znaleźć słabe punkty, a nam było tym trudniej, że większość trasy testowej przejechaliśmy w korku na Puławskiej rozkoszując się pięcioma trybami masażu, mocnym audio od Bose i telewizją cyfrową działającą do 10 km/h, a resztę na dziurawych drogach poza Warszawą, gdzie wykazało się seryjne, regulowane zawieszenie pneumatyczne.

Przyspieszenie jest piekielnie dobre i wręcz zaskakujące w mierzącej aż 5,14 m limuzynie. To jednak zasługa nie tylko skutecznego napedu, ale też znaku rozpoznawczego Audi - lekkiej, aluminiowej konstrukcji karoserii &lt;i&gt;Audi space frame&lt;/i&gt;, która samodzielnie waży zaledwie 231 kg! Pozostała część masy całkowitej 1995 kg (1830 kg dla 3.0 TDI) to moc, komfort, luksus, najlepsze materiały i skuteczne systemy bezpieczeństwa. A w hamowaniu tej masy pomagały nam opcjonalne, ceramiczne tarcze hamulcowe wzmocnione kompozytem węglowym. Robią wrażenie! Co jeszcze może spowodować opad szczęki w nowym A8?

Oświetlenie. Podczas nocnej jazdy, a takiej ostatnimi czasy nam nie brakuje, to jeden z najważniejszych elementów samochodu, dzięki którym możemy bezpiecznie dojechać do celu. Nowe światla przednie &lt;i&gt;Audi Matrix LED&lt;/i&gt; to przełom w rozwoju technologii oświetlenia drogi. Piszę to z całą świadomością i stanowczością, ponieważ nigdy nie czułem się tak pewnie podczas jazdy w nocy, jak za kierownicą Audi A8 podczas opisywanej właśnie pierwszej jazdy. konstrukcja lamp jest całkiem prosta i potencjalnie bezawaryjna, ponieważ nie posiada elementów ruchomych. Składają się z 25 diod LED pogrupowanych w 5 wiązek świetlnych na reflektor. Wystarczy włączyć tryb automatyczny świateł długich w terenie niezabudowanym i powyżej 30 km/h, aby zobaczyć, jak elektroniczny system sterowania światłami korzysta z możliwości wyłączenia lub przyciemnienia każdej z diod. 

Nadjeżdżający w naprzeciwka kierowcy są wycinani z oświetlanego obszaru, a jednocześnie system wygasza wiązkę z drugiej strony drogi, aby nie oślepiać kierowcy jadącego przed nami. W każdej chwili reszta naszego pola widzenia, wraz ze znakami drogowymi wokół drogi, jest oświetlana pełnym, silnym światłem. Światła korzystają też z danych GPS, aby doświetlać zakręty i skrzyżowania jeszcze zanim wykonamy jakikolwiek ruch kierownicą. Coś niesamowitego! Ale jest jeszcze coś. Kierunkowskazy LED nie świecą teraz w trybie 0/1, lecz rozświetlają się stopniowo w kierunku planowanego manewru, jeszcze dobitniej wskazując, gdzie zamierzamy skręcić. Dotyczy to zarówno przednich, jak i tylnych "migaczy". Ciekawy pomysł.

Ach, jeszcze jedna sprawa związana ze światłami. Kamera umieszczona w pierścieniach Audi z przodu pojazdu (widoczna na zdjęciach) potrafi wykrywać ludzi, którzy spacerują w nocy tam, gdzie nie powinni, często jescze ubrani na czarno. A8 potrafi ich wychwycić za pomocą kamery termowizyjnej i oświetlić trzykrotnym błyskiem, wyraźnie oddzielając ją od otoczenia. Większe zwierzęta też rozpoznaje, ale nie błyska - mogłoby to przestraszyć i zdezorientować zwierzę, co utrudniłoby bezpieczne ominięcie. Obraz z kamery możemy również wyświetlać na ekranie LCD pomiędzy analogowymi zegarami, co w niesprzyjających warunkach potrafi bardzo pomóc.

Poza tym mamy do dysposycji pełen wachlarz znanych już systemów, jak asystenci pasa ruchu i martwego pola, aktywny tempomat, kamery wokół auta z opcją top view i wiele innych. Zajmijmy sie teraz tym, co wyróżnia klasę luksusowych limuzyn... Pachnąca skóra &lt;i&gt;unikat&lt;/i&gt; to nowość w palecie Audi i najbardziej naturalna skóra w ofercie, garbowana przy użyciu wyłącznie naturalnych substancji ze środkowoeuropejskich roślin. Dzięki temu skóra jest naturalna, przyjemna w dotyku, a powierzchnia oddychająca. Posiada też wyjątkowy zapach. Wnętrze można również odzobić wyjątkowymi fornirami w kolorach brązowo-srebrnej topoli lub brązowo-złotego, autentycznie chropowatego jesionu. Szczególnie jesion zasługuje na uwagę, bo wygląda rewelacyjnie. A jeśli wszystko chcecie mieć po siebie - Audi Exclusive służy pomocą. Skóry na zamówienie, tworzone na zyczenie kolory nadwozia i wiele, wiele innych opcji dla najbardziej wymagających nie stanowi problemu. Jedynym może byc cena - ograniczona tylko z jednej strony...

A8 4.2 TDI clean diesel quattro to wydatek minimum 435 tysięcy złotych. Najtańszy w ofercie 3.0 TDI clean diesel quattro kosztuje 360 tysięcy, a najdroższy - 471 800 zł. To najmocniejsze 4.0 TFSI quattro w wersji Lang. Tym zdążyłem odbyć tylko krótką przejażdżkę na tylnym fotelu, oglądając telewizję na monitorze LCD, rozkoszując się ciszą i komfortem tylnego miejsca przedłużonej wersji.  Ale spokojnie - miejmy nadzieję, że nie będziemy musieli długo czekać na dłuższe spotkanie, na które pierwsza jazda wzbudziła spory apetyt. Nowe A8 z pewnością ma wszystko, czego potrzeba do nawiązania walki z najmocniejszymi konkurentami w klasie. Już wkrótce dowiemy się, czy tę walkę wygra.