---
slug: "nowa-skoda-octavia"
title: "Nowa Skoda Octavia"
brand: "Nowa"
model: "Skoda Octavia"
publishedAt: "2015-06-01"
lead: "# Nowa Skoda Octavia - Z rozsądkiem w genach  **Nowa Octavia to model, na którym spoczywa ogromna odpowiedzialność. Ma zastąpić samochód, który przez lata królował w rankingach sprzedaży, budując status czeskiej marki w naszym kraju. Czy nowa odsłona jest na to przygotowana? Okaz"
originalUrl: ""
tags: ["test"]
---

# Nowa Skoda Octavia - Z rozsądkiem w genach

**Nowa Octavia to model, na którym spoczywa ogromna odpowiedzialność. Ma zastąpić samochód, który przez lata królował w rankingach sprzedaży, budując status czeskiej marki w naszym kraju. Czy nowa odsłona jest na to przygotowana? Okazuje się, że geny Octavii są w niej aż zbyt silne.**

Dlaczego „zbyt silne”? Może dlatego, że wraz z nadejściem nowej generacji Czesi postanowili dodać swojemu modelowi nieco prestiżu, a ten nie wiedzieć czemu najlepiej czuje się w tańszych wersjach wyposażeniowych. A może to tylko nasze przyzwyczajenie do taniej i funkcjonalnej Octavii? Zaproszeni na pierwsze jazdy testowe sprawdzaliśmy to w najlepszy możliwy sposób.

Ale zanim zasiądziemy za kierownicą, należy wspomnieć, co i za ile w nowej Skodzie dostajemy. Otóż cennik otwiera wersja &lt;i&gt;Active&lt;/i&gt;, kosztująca 59 500 zł. Golas? Nie bardzo - klimatyzacja, elektryczne szyby z przodu, wejście USB i możliwość odtwarzania plików mp3 przez cztery głośniki, hamulec antykolizyjny, poduszki czołowe, boczne, kurtyny powietrzne oraz poduszka kolanowa kierowcy, światła do jazdy dziennej i... kilka rzeczy więcej, ale chyba nie ma sensu wymieniać wszystkiego. Chcę Wam po prostu zakomunikować, że jest to kompletnie wyposażony samochód do codziennej eksploatacji w rodzinie i w firmie. 

**Za „podstawowe” pieniądze** otrzymujemy auto z silnikiem 1.2 TSI w wariancie 85-konnym oraz tylne zawieszenie z belką skrętną oraz ogromną ilość miejsca z przodu oraz z tyłu, która sprawia wrażenie obcowania z autem z pogranicza segmentów C i D. Co więcej, jest to liftback z bagażnikiem o pojemności 590 litrów. Jest on tak ważną częścią tego auta, że został nawet wpisany na listę wyposażenia w cenniku. I wiecie co? Jest dostępny również w wersjach &lt;i&gt;Ambition&lt;/i&gt; oraz &lt;i&gt;Elegance&lt;/i&gt;. Bez dopłaty!

**Za kierownicą** najtańszej Octavii nie ma emocji. Elektryczne wspomaganie układu kierowniczego nie działa tak dobrze, jak w Golfie, za to skrzynia biegów działa równie precyzyjnie. Dynamika? Mizerna. Spalanie? Za wysokie, ponieważ auto jest odrobinę za ciężkie dla tego silnika, co wymaga zdecydowanego dodawania gazu w sytuacji, kiedy oczekujemy od auta większej werwy niż od lokomotywy parowej. 

**Jeżeli chodzi o wygodę**, nie ma tu nic do zarzucenia - z belki skrętnej nie da się wycisnąć lepszego kompromisu pomiędzy wygodą a prowadzeniem i tu nikt nic nie zepsuł. Felgi w rozmiarze 15 cali i na normalnych, drogowych oponach świetnie radzą sobie z dziurami, co w połączeniu z dobrym spasowaniem elementów tworzy w ciemnym, smutnym, „skodzianym” wnętrzu bardzo cichą atmosferę. Podsumowując - jest to do granic funkcjonalne auto, świetnie wykonane, zastosowane materiały są dobrej jakości, wygląda bardzo dobrze, a klient z pewnością ma poczucie dobrze wydanych pieniędzy.

**A co jest na drugim biegunie?** Octavia &lt;i&gt;Elegance&lt;/i&gt; z 2.0 TDI ze 150 KM pod maską, wyposażona w skrzynię DSG-6 i we wszystko, co można tu mieć. Cena przekracza 130 tysiecy, a wrażenia z jazdy są... mieszane. Felgi w rozmiarze 18 cali (za dopłatą, standardowo 17) sprawiają, że każda nierówność jest mocno odczuwalna i bardziej ją słychać. Na „kocich łbach” pojawiają się też świdrujące w głowie basy. To za duzy rozmiar dla rozsądnej „octy” i pomimo naprawdę świetnego wyglądu, pasującego do bardziej eleganckiej stylistyki, należy pozostać przy 15- i 16-calowych kołach. Jeżeli chodzi o dynamikę, auto wydaje się zdecydowanie za ciężkie, co sugeruje zaoszczędzenie 8000 zł na skrzyni DSG - zyskamy wtedy lepsze przyspieszenie i niższe zużycie paliwa. Drugą najbogatszą wersją nowej Octavii był model z silnikiem 1.8 TSI o mocy 180 KM ze skrzynią DSG-7, która nawet w trybie sportowym systemu &lt;i&gt;DRIVE SET UP&lt;/i&gt; (+ 1700 zł) zmieniała biegi zbyt wolno i gubiła się w doborze przełożeń, a jeździliśmy nią tylko 20 minut. Wydawać by się mogło, że 180 KM to dużo, ale przyspieszenia były pozbawione dramatyzmu. Pewnie dlatego, że takie auto waży przeszło 200 kg więcej od wersji z mniejszym silnikiem i ręczną skrzynią. To tak, jakbyśmy w każdą podróż zabierali dwóch pasażerów „przy kości”. Jest sens?

**Gadżety**, jakie można sobie teraz zamówić w Skodzie zadowolą najbardziej wybrednych klientów z pokaźnymi portfelami, ale czy tacy szukają ofert u czeskiego producenta? Pojawił się system &lt;i&gt;Columbus&lt;/i&gt;, czyli nowoczesny, pojemnościowy wyświetlacz LCD o przekątnej 8 cali z czujnikiem zbliżeniowym, który powiększa ikony tylko w momencie zbliżania ręki do ekranu. Odtwarza DVD, nawigacja jest bez zarzutu, obsługa jest intuicyjna a pamięć o pojemności 64 GB robi wrażenie. Cena również - 7 300 zł dla wersji &lt;i&gt;Ambition&lt;/i&gt; oraz 6 700 zł dla &lt;i&gt;Elegance&lt;/i&gt;. 

**Z nowoczesności** warto odnotować też pełen wachlarz asystentów kierowcy, w tym asystenta parkowania w wersji 2.0, który poza zwiększoną prędkością skanowania potrafi również zaparkować prostopadle! Przynajmniej w teorii, bo nie każdy się z systemem „dogadywał”. Korzystania z tej funkcji trzeba się nauczyć, jednak z odrobiną wprawy ze strony kierowcy działa bez zarzutu, szybko i sprawnie parkując auto, oczywiście również równolegle. Z wersją 2.0 system zyskał też funkcję hamowania awaryjnego oraz wyjazdu z miejsca parkingowego. Cena? Niezbyt wygórowana - dla wersji &lt;i&gt;Elegance&lt;/i&gt; to tylko 850 zł, a do &lt;i&gt;Ambition&lt;/i&gt; można go dokupić za 2000 zł. Wszystkie inne systemy, które znamy już z aut Volkswagena i o których pisaliśmy przy okazji testów, również zawitały do Skody, jednak cena, jaką należy zapłacić za tak wyposażone auto nie pasuje do auta z kurą w logo.

Bardzo ciekawą odmianą nowej Octavii jest wersja &lt;i&gt;Ambition&lt;/i&gt; z silnikiem 1.4 TSI o mocy 140 KM z manualną skrzynią. Dynamika jest bardziej odczuwalna, cena niższa, a dość bogate wyposażenie można łatwo wzbogacić we wszystkie opcje z cennika, niedostępne dla wersji „budżetowej”.

**Więc jak Octavia wypada w porównaniu z konkurencją? **Miażdży i rządzi! Jeśli chodzi o ilość miejsca w środku i w bagazniku oraz ogólną praktyczność, rzecz jasna. Cenowo wypada nieźle, choć oczywiście znajdą się tańsze propozycje. Niestety, nie prowadzi się tak dobrze, jak konkurenci z Korei, Japonii i Niemiec, za to przewyższa pod tym względem Francję. Wygląd? Sprawa dyskusyjna i kwestia gustu, ale poważniejszy i bardziej dynamiczny design sprawia bardzo pozytywne wrażenie. Wszystkie modele segmentu C mają bardzo duże możliwości konfiguracji i wiele ciekawych gadżetów w cennikach, lecz jeżeli klient będzie szukał jak najbardziej praktycznego auta w jak najlepszej cenie, Czesi mogą być spokojni - trafi do salonu Skody.